server:
  port: 8002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
spring:
  datasource:
    url: jdbc:sqlite:auth.db
    username: admin
    password: admin
    driver-class-name: org.sqlite.JDBC
  jpa:
    #    database-platform: com.springboot.sqlite.SQLDialect
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  application:
    name: auth-service
  config:
    import: "optional:configserver:http://localhost:9000"
